name: practicas_as ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1.15.2
        with:
          otp-version: 25.2
          rebar3-version: 3.20.0
      - name: Checks
        run: |
          rebar3 dialyzer
          rebar3 proper -c true
          rebar3 cover -m 100
