name: practicas_as ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: erlang:25
      options: "--entrypoint /bin/bash"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checks
        run: >
          - rebar3 dialyzer
          - rebar3 proper -c true
          - rebar3 cover -m 100
